import type { ExportItem } from "@/lib/exportFormat";
import type { NewInventoryItemRow } from "@/lib/schema";

// Conflict strategies ported from DataImporter.kt's ImportConflictStrategy.
// Existing items are matched BY ID, exactly as the Android importer does.
export const IMPORT_STRATEGIES = ["SKIP_EXISTING", "REPLACE_EXISTING", "IMPORT_AS_NEW"] as const;
export type ImportStrategy = (typeof IMPORT_STRATEGIES)[number];

export interface ImportResult {
  totalItems: number;
  importedItems: number;
  skippedItems: number;
  errors: string[];
}

/**
 * Map one archived item onto a database row.
 *
 * `imageKey` is the Netlify Blobs key the caller obtained by uploading the
 * archive's `images/<imageFileName>` entry; the archive's own filename is
 * device-local and meaningless here.
 *
 * `keepId` controls the identity column. REPLACE_EXISTING overwrites a specific
 * row so it must carry the original id; IMPORT_AS_NEW omits it and lets
 * Postgres assign one, matching the Kotlin importer's `id = 0` sentinel.
 *
 * createdAt/updatedAt are epoch milliseconds in the archive (Kotlin
 * System.currentTimeMillis) and timestamptz in Postgres.
 */
export function toRow(
  item: ExportItem,
  imageKey: string | null,
  keepId: boolean,
): NewInventoryItemRow {
  const row: NewInventoryItemRow = {
    title: item.title,
    description: item.description,
    purchasePrice: item.purchasePrice,
    sellingPrice: item.sellingPrice,
    purchaseDate: item.purchaseDate,
    scheduledPostDate: item.scheduledPostDate,
    postedDate: item.postedDate,
    soldDate: item.soldDate,
    imageKey,
    purchaseLocation: item.purchaseLocation,
    category: item.category,
    site: item.site,
    notes: item.notes,
    createdAt: new Date(item.createdAt),
    updatedAt: new Date(item.updatedAt),
  };
  if (keepId) row.id = item.id;
  return row;
}

export interface PlannedItem {
  row: NewInventoryItemRow;
  /** Overwrite this existing id rather than inserting a new row. */
  replaceId: number | null;
}

export interface ImportPlan {
  inserts: PlannedItem[];
  skipped: number;
}

/**
 * Decide what to do with each archived item, given the ids already present.
 *
 * Pure so the branching can be tested without a database. Follows the `when`
 * block in DataImporter.importFromZip with one deliberate departure: an item
 * whose id is NOT already present keeps that id, where the Android importer
 * would assign a fresh one.
 *
 * That matters because this app is seeded by importing a backup into an empty
 * database. Reassigning ids there would make the very first import lose every
 * original id, and a later re-import of the same archive would then match
 * nothing — SKIP_EXISTING would silently duplicate the entire inventory
 * instead of skipping it. Preserving ids keeps import idempotent and makes a
 * partially-failed run safe to repeat. The identity sequence is advanced
 * afterwards so autogenerated ids do not collide (see resyncItemSequence).
 */
export function planImport(
  items: ExportItem[],
  existingIds: ReadonlySet<number>,
  strategy: ImportStrategy,
  imageKeys: ReadonlyMap<string, string>,
): ImportPlan {
  const inserts: PlannedItem[] = [];
  let skipped = 0;

  for (const item of items) {
    const imageKey = item.imageFileName ? imageKeys.get(item.imageFileName) ?? null : null;
    const exists = existingIds.has(item.id);

    if (exists && strategy === "SKIP_EXISTING") {
      skipped++;
      continue;
    }
    if (exists && strategy === "REPLACE_EXISTING") {
      inserts.push({ row: toRow(item, imageKey, true), replaceId: item.id });
      continue;
    }
    if (exists) {
      // IMPORT_AS_NEW against a colliding id: deliberately duplicate under a
      // fresh id, which is the whole point of the strategy.
      inserts.push({ row: toRow(item, imageKey, false), replaceId: null });
      continue;
    }
    // No row holds this id, so keep the archive's own. See the note above on
    // why this departs from the Android importer.
    inserts.push({ row: toRow(item, imageKey, true), replaceId: null });
  }

  return { inserts, skipped };
}
