import { sql, inArray } from "drizzle-orm";
import type { PgAsyncDatabase } from "drizzle-orm/pg-core";
import { getDb } from "@/lib/db";
import { categories, inventoryItems, sites } from "@/lib/schema";
import { planImport, type ImportStrategy } from "@/lib/importMapping";
import type { ExportItem } from "@/lib/exportFormat";

export interface BatchOutcome {
  imported: number;
  skipped: number;
}

// The shared base class every Postgres driver extends. Accepting it — rather
// than the Netlify driver concretely — lets the tests drive these functions
// against a real in-process Postgres, so the import path that runs in
// production is the one under test.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type ImportDb = PgAsyncDatabase<any, any>;

/**
 * Apply one batch of archived items.
 *
 * The whole batch runs in a transaction so a failure part-way cannot leave the
 * inventory half-imported.
 */
export async function importItemBatch(
  items: ExportItem[],
  strategy: ImportStrategy,
  imageKeys: ReadonlyMap<string, string>,
  database?: ImportDb,
): Promise<BatchOutcome> {
  const db = database ?? (getDb() as ImportDb);
  const ids = items.map((i) => i.id);

  const existing = ids.length
    ? await db
        .select({ id: inventoryItems.id })
        .from(inventoryItems)
        .where(inArray(inventoryItems.id, ids))
    : [];
  const existingIds = new Set(existing.map((r) => r.id));

  const plan = planImport(items, existingIds, strategy, imageKeys);
  if (plan.inserts.length === 0) return { imported: 0, skipped: plan.skipped };

  // Any row carrying an explicit id bypasses the identity sequence, whether it
  // is a replacement or a first insert that preserved its archived id.
  const wroteExplicitId = plan.inserts.some((p) => p.row.id !== undefined);

  for (const planned of plan.inserts) {
    if (planned.replaceId !== null) {
      await db
        .insert(inventoryItems)
        .values(planned.row)
        .onConflictDoUpdate({ target: inventoryItems.id, set: planned.row });
    } else {
      await db.insert(inventoryItems).values(planned.row);
    }
  }

  // An explicit-id write bypasses the identity sequence, which keeps counting
  // from wherever it was. Without this the next autogenerated id collides with
  // an imported row and the insert fails on the primary key.
  if (wroteExplicitId) await resyncItemSequence(db);

  return { imported: plan.inserts.length, skipped: plan.skipped };
}

/** Advance the identity sequence past the highest existing id. */
export async function resyncItemSequence(database?: ImportDb): Promise<void> {
  const db = database ?? (getDb() as ImportDb);
  await db.execute(sql`
    select setval(
      pg_get_serial_sequence('inventory_items', 'id'),
      coalesce((select max(id) from inventory_items), 0) + 1,
      false
    )
  `);
}

/** Insert category and site names, ignoring ones already present. Both are
 *  simple name lists in the archive. */
export async function importLookups(
  categoryNames: string[],
  siteNames: string[],
  database?: ImportDb,
): Promise<void> {
  const db = database ?? (getDb() as ImportDb);
  const cats = categoryNames.filter((n) => n.trim().length > 0);
  const sts = siteNames.filter((n) => n.trim().length > 0);
  if (cats.length) {
    await db.insert(categories).values(cats.map((name) => ({ name }))).onConflictDoNothing();
  }
  if (sts.length) {
    await db.insert(sites).values(sts.map((name) => ({ name }))).onConflictDoNothing();
  }
}
