import {
  pgTable, bigint, text, numeric, date, timestamp, index,
} from "drizzle-orm/pg-core";

// Port of the Android app's Room entities (data/model/*.kt).
//
// Three deliberate departures from a literal translation, each load-bearing:
//
// 1. IDs are `GENERATED BY DEFAULT AS IDENTITY`, never `ALWAYS`. The importer's
//    REPLACE_EXISTING strategy writes explicit ids taken from a backup, which
//    `ALWAYS` rejects outright. See importItems() for the sequence resync that
//    an explicit-id write requires.
// 2. Money is `numeric(10,2)`, not double precision. Room used Double; float
//    money drifts across the analytics SUMs. `mode: "number"` keeps the
//    TypeScript surface a plain number while Postgres stores exact decimals.
// 3. The four date fields are `date`, not `timestamptz`. They are LocalDate in
//    Kotlin — calendar days with no timezone. Storing them as instants would
//    shift the day across timezone boundaries.
//
// `status` and `profit` are NOT columns. They are computed from which date
// fields are non-null; see itemStatus.ts. Storing them would let them drift
// out of agreement with the dates they are derived from.
export const inventoryItems = pgTable("inventory_items", {
  id: bigint("id", { mode: "number" }).primaryKey().generatedByDefaultAsIdentity(),
  title: text("title").notNull(),
  description: text("description").notNull().default(""),
  purchasePrice: numeric("purchase_price", { precision: 10, scale: 2, mode: "number" }).notNull(),
  sellingPrice: numeric("selling_price", { precision: 10, scale: 2, mode: "number" }),
  purchaseDate: date("purchase_date").notNull(),
  scheduledPostDate: date("scheduled_post_date"),
  postedDate: date("posted_date"),
  soldDate: date("sold_date"),
  // Netlify Blobs key, replacing Room's on-device `imagePath` file path.
  imageKey: text("image_key"),
  purchaseLocation: text("purchase_location").notNull().default(""),
  category: text("category").notNull().default(""),
  site: text("site").notNull().default(""),
  notes: text("notes").notNull().default(""),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => [
  // Mirrors the query shapes in InventoryDao.kt: getItemsScheduledBetween,
  // getSoldItems, getPostedItems, and getAllItems ORDER BY createdAt DESC.
  index("inventory_scheduled_idx").on(t.scheduledPostDate),
  index("inventory_sold_idx").on(t.soldDate),
  index("inventory_posted_idx").on(t.postedDate),
  index("inventory_created_idx").on(t.createdAt),
]);

export const categories = pgTable("categories", {
  id: bigint("id", { mode: "number" }).primaryKey().generatedByDefaultAsIdentity(),
  name: text("name").notNull().unique(),
});

export const sites = pgTable("sites", {
  id: bigint("id", { mode: "number" }).primaryKey().generatedByDefaultAsIdentity(),
  name: text("name").notNull().unique(),
});

// Brute-force protection for the single shared passphrase (see loginRateLimit.ts).
// Keyed on a salted hash of the client IP — never the address itself, and never
// the submitted passphrase.
export const loginAttempts = pgTable("login_attempts", {
  ipHash: text("ip_hash").primaryKey(),
  failures: bigint("failures", { mode: "number" }).notNull().default(0),
  lastFailureAt: timestamp("last_failure_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => [
  index("login_attempts_last_failure_idx").on(t.lastFailureAt),
]);

export type InventoryItemRow = typeof inventoryItems.$inferSelect;
export type NewInventoryItemRow = typeof inventoryItems.$inferInsert;
