import { describe, it, expect } from "vitest";
import { freshDrizzle } from "../helpers/pg";
import { importItemBatch, importLookups } from "@/lib/importItems";
import type { ExportItem } from "@/lib/exportFormat";

const item = (o: Partial<ExportItem> = {}): ExportItem => ({
  id: 1, title: "Item", description: "", purchasePrice: 10, sellingPrice: null,
  purchaseDate: "2026-01-01", scheduledPostDate: null, postedDate: null, soldDate: null,
  imageFileName: null, purchaseLocation: "", category: "", site: "", notes: "",
  createdAt: 1737000000000, updatedAt: 1738000000000, ...o,
});

const rows = (client: Awaited<ReturnType<typeof freshDrizzle>>["client"]) =>
  client.query<{ id: string; title: string; purchase_price: string; image_key: string | null }>(
    `select id, title, purchase_price::text, image_key from inventory_items order by id`,
  );

describe("importItemBatch", () => {
  it("imports items into an empty database", async () => {
    const { db, client } = await freshDrizzle();
    const out = await importItemBatch(
      [item({ id: 1, title: "Lamp", purchasePrice: 12.5, imageFileName: "a.jpg" }),
       item({ id: 2, title: "Chair", purchasePrice: 40 })],
      "IMPORT_AS_NEW",
      new Map([["a.jpg", "abc123"]]),
      db,
    );
    expect(out).toEqual({ imported: 2, skipped: 0 });

    const r = await rows(client);
    expect(r.rows.map((x) => x.title)).toEqual(["Lamp", "Chair"]);
    // Seeding an empty database preserves the archive's ids, so a repeat run
    // can recognise these rows instead of duplicating them.
    expect(r.rows.map((x) => Number(x.id))).toEqual([1, 2]);
    expect(r.rows[0].purchase_price).toBe("12.50");
    expect(r.rows[0].image_key).toBe("abc123");
    await client.close();
  });

  it("SKIP_EXISTING leaves the stored row untouched", async () => {
    const { db, client } = await freshDrizzle();
    await importItemBatch([item({ id: 5, title: "Original" })], "REPLACE_EXISTING", new Map(), db);
    const out = await importItemBatch(
      [item({ id: 5, title: "Incoming" })], "SKIP_EXISTING", new Map(), db,
    );
    expect(out).toEqual({ imported: 0, skipped: 1 });
    const r = await rows(client);
    expect(r.rows).toHaveLength(1);
    expect(r.rows[0].title).toBe("Original");
    await client.close();
  });

  it("REPLACE_EXISTING overwrites in place without duplicating", async () => {
    const { db, client } = await freshDrizzle();
    await importItemBatch([item({ id: 5, title: "Original" })], "REPLACE_EXISTING", new Map(), db);
    const out = await importItemBatch(
      [item({ id: 5, title: "Updated", purchasePrice: 99.99 })],
      "REPLACE_EXISTING", new Map(), db,
    );
    expect(out).toEqual({ imported: 1, skipped: 0 });
    const r = await rows(client);
    expect(r.rows).toHaveLength(1);
    expect(r.rows[0].title).toBe("Updated");
    expect(r.rows[0].purchase_price).toBe("99.99");
    await client.close();
  });

  it("IMPORT_AS_NEW duplicates an existing id under a fresh one", async () => {
    const { db, client } = await freshDrizzle();
    await importItemBatch([item({ id: 5, title: "First" })], "REPLACE_EXISTING", new Map(), db);
    await importItemBatch([item({ id: 5, title: "Second" })], "IMPORT_AS_NEW", new Map(), db);
    const r = await rows(client);
    expect(r.rows).toHaveLength(2);
    expect(new Set(r.rows.map((x) => x.id)).size).toBe(2);
    await client.close();
  });

  // Re-importing the same archive must be a no-op, not a second copy. This is
  // what preserving ids on a fresh insert buys.
  it("is idempotent when the same archive is imported twice", async () => {
    const { db, client } = await freshDrizzle();
    const archive = [item({ id: 1, title: "Lamp" }), item({ id: 2, title: "Chair" })];
    await importItemBatch(archive, "SKIP_EXISTING", new Map(), db);
    const second = await importItemBatch(archive, "SKIP_EXISTING", new Map(), db);
    expect(second).toEqual({ imported: 0, skipped: 2 });
    expect((await rows(client)).rows).toHaveLength(2);
    await client.close();
  });

  // The regression this guards: writing explicit ids leaves the identity
  // sequence behind, so the next autogenerated id collides on the primary key.
  it("keeps autogenerated ids working after an explicit-id import", async () => {
    const { db, client } = await freshDrizzle();
    await importItemBatch(
      [item({ id: 100, title: "High id" }), item({ id: 101, title: "Higher" })],
      "IMPORT_AS_NEW", new Map(), db,
    );
    // Colliding ids force autogeneration, which is exactly the path that fails
    // with a duplicate-key error if the sequence was left behind.
    await importItemBatch(
      [item({ id: 100, title: "Duplicate" })], "IMPORT_AS_NEW", new Map(), db,
    );
    const r = await rows(client);
    expect(r.rows).toHaveLength(3);
    const fresh = r.rows.find((x) => x.title === "Duplicate")!;
    expect(Number(fresh.id)).toBeGreaterThan(101);
    await client.close();
  });

  it("round-trips money and dates exactly", async () => {
    const { db, client } = await freshDrizzle();
    await importItemBatch(
      [item({ purchasePrice: 0.1, sellingPrice: 19.99, purchaseDate: "2026-03-01", soldDate: "2026-04-15" })],
      "IMPORT_AS_NEW", new Map(), db,
    );
    const r = await client.query<{ purchase_price: string; selling_price: string; purchase_date: string; sold_date: string }>(
      `select purchase_price::text, selling_price::text, purchase_date::text, sold_date::text from inventory_items`,
    );
    expect(r.rows[0]).toEqual({
      purchase_price: "0.10", selling_price: "19.99",
      purchase_date: "2026-03-01", sold_date: "2026-04-15",
    });
    await client.close();
  });
});

describe("importLookups", () => {
  it("inserts names once, tolerating repeats across batches", async () => {
    const { db, client } = await freshDrizzle();
    await importLookups(["Lighting", "Seating"], ["Etsy"], db);
    await importLookups(["Lighting"], ["Etsy", "eBay"], db);
    const cats = await client.query<{ name: string }>(`select name from categories order by name`);
    const sts = await client.query<{ name: string }>(`select name from sites order by name`);
    expect(cats.rows.map((r) => r.name)).toEqual(["Lighting", "Seating"]);
    expect(sts.rows.map((r) => r.name)).toEqual(["Etsy", "eBay"]);
    await client.close();
  });

  it("ignores blank names", async () => {
    const { db, client } = await freshDrizzle();
    await importLookups(["", "  "], [], db);
    const cats = await client.query(`select name from categories`);
    expect(cats.rows).toHaveLength(0);
    await client.close();
  });
});
