CREATE TABLE "categories" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "categories_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" text NOT NULL UNIQUE
);
--> statement-breakpoint
CREATE TABLE "inventory_items" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "inventory_items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"title" text NOT NULL,
	"description" text DEFAULT '' NOT NULL,
	"purchase_price" numeric(10,2) NOT NULL,
	"selling_price" numeric(10,2),
	"purchase_date" date NOT NULL,
	"scheduled_post_date" date,
	"posted_date" date,
	"sold_date" date,
	"image_key" text,
	"purchase_location" text DEFAULT '' NOT NULL,
	"category" text DEFAULT '' NOT NULL,
	"site" text DEFAULT '' NOT NULL,
	"notes" text DEFAULT '' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "login_attempts" (
	"ip_hash" text PRIMARY KEY,
	"failures" bigint DEFAULT 0 NOT NULL,
	"last_failure_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "sites" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sites_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" text NOT NULL UNIQUE
);
--> statement-breakpoint
CREATE INDEX "inventory_scheduled_idx" ON "inventory_items" ("scheduled_post_date");--> statement-breakpoint
CREATE INDEX "inventory_sold_idx" ON "inventory_items" ("sold_date");--> statement-breakpoint
CREATE INDEX "inventory_posted_idx" ON "inventory_items" ("posted_date");--> statement-breakpoint
CREATE INDEX "inventory_created_idx" ON "inventory_items" ("created_at");--> statement-breakpoint
CREATE INDEX "login_attempts_last_failure_idx" ON "login_attempts" ("last_failure_at");